[tox]
envlist = py{310,311,312,313}-{test,notebooks}
requires = pip >= 18.0
           hatchling
isolated_build = true

[testenv]
changedir =
    test: .tmp/{envname}
    notebooks: examples
deps =
    test: notebook<7
    notebooks: numpy
    notebooks: ipyvuetify
    notebooks: scikit-image
    notebooks: notebook<7
    visual: pytest-ipywidgets[all]
    visual: pytest-playwright==0.5.2
    visual: starlette<0.47
extras =
    test: test
    notebooks: test
commands =
    test: pip freeze
    test: pytest --pyargs bqplot_image_gl --cov bqplot_image_gl -p no:warnings {posargs}
    test: python {toxinidir}/.check_extension.py
    notebooks: python .validate-notebooks.py
    visual: playwright install chromium
    visual: pytest tests/ui {posargs}

[testenv:codestyle]
deps = flake8
skip_install = true
commands =
    flake8 --max-line-length=100 bqplot_image_gl
